<template>
  <v-app>
    <!-- 顶部导航栏 -->
    <v-app-bar color="primary" elevation="2" height="40" id="title-bar" class="pywebview-drag-region">
      <v-app-bar-title class="text-body-2">
        <v-icon icon="mdi-book-open-page-variant" size="small" class="mr-1"></v-icon>
        OneShot
      </v-app-bar-title>
      <template v-slot:append>
        <v-btn icon="mdi-theme-light-dark" variant="text" size="small" @click="toggleTheme" class="no-drag"></v-btn>
        <v-btn icon="mdi-close" variant="text" size="small" @click="onClose" class="no-drag"></v-btn>
      </template>
    </v-app-bar>

    <!-- 主内容：设置面板 -->
    <v-main class="main-content pt-12 px-2 pb-2">
      <SettingsPanel 
        :debug-mode="debugMode"
        :show-result-dialog="showResultDialog"
        :test-papers="testPapers"
        @apply-hotkey="onApplyHotkey"
        @update-config="onUpdateConfig"
        @show-test-dialog="showResultDialog = true"
        @update:show-result-dialog="(val: boolean) => showResultDialog = val"
      />
    </v-main>

    <!-- 底部 -->
    <v-footer app class="text-caption py-1">
      Vue 3 + Vuetify
    </v-footer>

    <!-- 提示组件 -->
    <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
      {{ snackbar.text }}
    </v-snackbar>

  </v-app>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useTheme } from 'vuetify'
import SettingsPanel from './components/SettingsPanel.vue'
import { hideWindow } from './api'

// Theme
const theme = useTheme()
const toggleTheme = () => {
  theme.global.name.value = theme.global.current.value.dark ? 'light' : 'dark'
}

// 关闭按钮 → 隐藏窗口，保留托盘
function onClose() {
  hideWindow()
}

// ESC 隐藏窗口
function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'Escape') hideWindow()
}

onMounted(() => document.addEventListener('keydown', onKeyDown))
onUnmounted(() => document.removeEventListener('keydown', onKeyDown))

// Debug mode
const debugMode = ref(true)

// Snackbar
const snackbar = ref({
  show: false,
  text: '',
  color: 'success',
})

// 测试数据
const showResultDialog = ref(true)
const testPapers = ref([
  {
    title: 'Contraction Hierarchies: Faster and Simpler Hierarchical Routing in Road Networks',
    authors: ['Robert Geisberger', 'Peter Sanders', 'Dominik Schultes', 'Daniel Delling'],
    year: 2008,
    citation_index: '19',
    ccf_rank: 'B',
    doi: '10.1007/978-3-540-68552-4_24',
    abstract: 'We present a route planning technique solely based on the concept of node contraction. The nodes are first ordered by importance. A hierarchy is then generated by iteratively contracting the least important node.',
    citation_count: 1500,
  },
  {
    title: 'Data structures for categorical path counting queries',
    authors: ['Meng He', 'Serikzhan Kazi'],
    year: 2022,
    citation_index: '1',
    ccf_rank: 'A',
    doi: '10.1016/j.tcs.2022.01.023',
    abstract: 'Consider an ordinal tree T on n nodes, each of which is assigned a category from an alphabet.',
  },
])

// 设置事件
function onApplyHotkey(hotkey: { modifiers: string[], key: string }) {
  console.log('应用快捷键:', hotkey)
  snackbar.value = { show: true, text: `快捷键: ${hotkey.modifiers.join('+')}+${hotkey.key.toUpperCase()}`, color: 'success' }
}

function onUpdateConfig(key: string, value: any) {
  console.log('更新配置:', key, value)
}

// function onDownloadPaper(paper: any) {
//   console.log('下载论文:', paper.title)
//   snackbar.value = { show: true, text: '开始下载...', color: 'info' }
// }

// function onOpenPaperUrl(paper: any) {
//   console.log('打开论文链接:', paper.title)
//   const doiUrl = paper.doi ? `https://doi.org/${paper.doi}` : null
//   if (doiUrl) {
//     window.open(doiUrl, '_blank')
//   }
// }
</script>

<style>
/* 主内容区域可滚动 */
.main-content {
  overflow-y: auto;
  height: calc(100vh - 40px - 24px); /* 减去 app-bar 和 footer */
}

/* 标题栏拖动样式 */
#title-bar {
  cursor: move;
  user-select: none;
}

.no-drag {
  cursor: default !important;
}
</style>
